import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">

        Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit aliquid rem quis quia. Incidunt officiis placeat quia accusamus id aut aperiam tempore voluptate. Vel beatae, sequi quisquam natus corrupti saepe?
      </main>
    </div>
  );
}
