import Head from "next/head";
import Image from "next/image";
import bgimage from "../public/bg.svg";

import { ImSearch } from "react-icons/im";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="input--container">
          <h1>Start your Search</h1>

          
          <div class=""></div>
          <input className="input--text" type="text" placeholder="Search" />

          <ImSearch />
        </div>
        x{" "}
      </main>
    </div>
  );
}
